name: Deploy Hexo Blog

on:
  push:
    branches:
      - main  # 触发条件：推送到main分支
  pull_request:
    branches:
      - main  # 触发条件：PR到main分支
  workflow_dispatch:  # 手动触发

# 设置权限
permissions:
  contents: write  # 允许写入仓库内容
  pages: write     # 允许写入GitHub Pages
  id-token: write  # 允许写入ID令牌（用于Pages部署）

# 允许并发运行，但取消进行中的运行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive  # 如果使用子模块

      # 2. 设置Node.js环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 3. 安装Hexo CLI（如果需要）
      - name: Install Hexo CLI
        run: |
          npm install -g hexo-cli

      # 4. 安装依赖
      - name: Install dependencies
        run: |
          npm install

      # 5. 清理缓存
      - name: Clean cache
        run: |
          hexo clean

      # 6. 生成静态文件
      - name: Generate static files
        run: |
          hexo generate

      # 7. 设置Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 8. 上传构建产物
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # 可选：部署到自定义服务器
  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate site
        run: |
          hexo clean
          hexo generate

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_TARGET_DIR }}
          EXCLUDE: "/dist/, /node_modules/"
